version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports_node
    restart: always
    ports:
      - ${NODE_PORT}:3030
    volumes:
      - ./:/usr/src/app
    networks:
      - sports_network
  mongo:
    image: mongo:latest
    container_name: sports_mongo
    restart: always
    environment:
      MONGODB_DATABASE: sports
    ports:
      - "27017:27017"
    networks:
      - sports_network

  mongo-express:
    image: mongo-express
    container_name: sports_mongo-express
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./data/db/mongoExpress:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - sports_network

volumes:
  mongo:
    driver: local
  mongo-express:
    driver: local
  node:
    driver: local

networks:
  sports_network:
    driver: bridge